[package]
name = "cgcamera"
version = "0.2.3"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]
edition = "2018"

[lib]
name = "cgcamera"

[dependencies]
simple_cgmath = { git = "https://github.com/stallmanifold/simple-cgmath" }
